### PR TITLE
feat: Add link for card

### PR DESCRIPTION
**Pull request by obgibson**
### Requirements for a pull request

Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.

- [ ] Unit tests related to the change have been updated 
- [ ] Documentation related to the change has been updated 

### Description of the Change

Added a link to the top of the card display for easy access to the card URL for sharing.

Screen Shot 2023-01-03 at 10 38 57 AM

### Alternate Designs

\-

### Possible Drawbacks

\-

### Verification Process

Navigate to a task with a card. See the link button. Click on the link button to open the card in its own tab.

### CODE REVIEW

**Comment by jimbudarz** [comment]
I tend to see the [link](https://duckduckgo.com/?q=link+icon&t=ffab&ia=web) symbol copy the URL to the clipboard, while there's a [box with an arrow](https://duckduckgo.com/?t=ffab&q=open+external+icon&ia=web) that more often indicates that something will open in a new window/tab.

**Comment by obgibson** [comment]
Would you prefer a button to copy the link? Or a link itself?

**Comment by jimbudarz** [comment]
> Would you prefer a button to copy the link? Or a link itself?

Either one would be useful, but what you've done here is even better than what I originally suggested.
My original desire was to have a link that would let users share the URL of a card with their team, so just a link to part of the page... Having an "open in new tab" button might be even better, to be honest- I would just change the icon.

**Comment by obgibson** [comment]
Updated

Screen Shot 2023-01-04 at 9 23 08 AM

**Pull request merged**
