### PR TITLE
fix: Replacing tags correctly when arriving from run page

### PR DESCRIPTION
**Pull request by rsanteri**
### Description of the Change

Fixing issue #54. Desired tag was getting replaced by cached values

### CODE REVIEW

**Review by obgibson — COMMENTED** [review]
Can you give some more detailed instructions on how to test this?

**Comment by romain-intel** [comment]
To test:
- go to the UI
 - select a tag (any tag will do)
 - confirm that in the left hand side, you now have that tag selected
 - create a new browser window and copy the URL that you have that contains the tag, something like http://ui_url:5000/?_tags=mftest_group%3Ab36ff4e0
 - paste that URL but modify the tag at the end (so change its value to something else)
 - when you load the page, you will see that the old tag is still selected and not the one you passed in the URL.

This does it for other things too like flow names and what not.

**Comment by rsanteri** [comment]
Tested also with flow_id, user and other filters. This PR fixes this behavior. UI was thinking we had default parameters if only one filter was selected and in that case we check if there is previous settings available.

**Review by obgibson — APPROVED** [review]
Works as expected

**Pull request merged**
